apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.10-172.18.0.20 #kubectl get node -owide (provide the IP range within the node ip)
